# -*- coding: utf-8 -*-
"""app_compensar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WA26wsXB12hQAwL7glX3Rg3qeLZGUgrc
"""

import streamlit as st
import auxiliar as aux

st.set_page_config(
    page_title="Compensar Demo: scoring crediticio"
)